name = "servewell-server"
main = "src/index.ts"
compatibility_date = "2026-05-19"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "servewell-db"
database_id = "dc36bf23-7787-4424-a48f-48cbe0e5528d"
migrations_dir = "migrations"