INSERT INTO serving_areas (
  id,
  organization_id,
  form_id,
  slug,
  name,
  category,
  description,
  public_note,
  requires_background_check,
  requires_training,
  requires_audition_or_interview,
  recruitment_status,
  sort_order
) VALUES
  (1, 1, 1, 'worship-singer', 'Worship Team / Singer', 'worship', 'Help lead the church in worship through singing.', 'This role may require rehearsal availability and an audition or conversation with the worship leader.', 0, 0, 1, 'open', 10),
  (2, 1, 1, 'bass-player', 'Bass Player', 'worship', 'Serve with the worship team as a bass player.', 'This role may require rehearsal availability and an audition or conversation with the worship leader.', 0, 0, 1, 'open', 20),
  (3, 1, 1, 'other-instrumentalist', 'Other Instrumentalist', 'worship', 'Serve with the worship team using another instrument.', 'This role may require rehearsal availability and an audition or conversation with the worship leader.', 0, 0, 1, 'open', 30),
  (4, 1, 1, 'slides', 'Slides', 'media_tech', 'Run worship lyrics, sermon slides, and other presentation elements.', 'Training may be provided before serving independently.', 0, 1, 0, 'open', 40),
  (5, 1, 1, 'sound', 'Sound', 'media_tech', 'Help with audio setup and live sound during services or events.', 'Training may be provided before serving independently.', 0, 1, 0, 'open', 50),
  (6, 1, 1, 'camera-livestream', 'Camera / Livestream', 'media_tech', 'Help operate cameras or livestream equipment for services.', 'This role is usually connected to Sunday morning services.', 0, 1, 0, 'open', 60),
  (7, 1, 1, 'kids-ministry', 'Kids Ministry', 'kids_youth', 'Serve children and families through kids ministry.', 'This role requires a background check before serving.', 1, 1, 0, 'open', 70),
  (8, 1, 1, 'youth-ministry', 'Youth Ministry', 'kids_youth', 'Serve students through youth ministry gatherings and events.', 'This role usually requires Wednesday night availability and a background check.', 1, 1, 0, 'open', 80),
  (9, 1, 1, 'greeting-hospitality', 'Greeting / Hospitality', 'hospitality', 'Welcome people and help create a warm Sunday experience.', NULL, 0, 0, 0, 'open', 90),
  (10, 1, 1, 'setup-cleanup', 'Setup / Cleanup', 'general', 'Help prepare spaces before services or events and reset them afterward.', NULL, 0, 0, 0, 'open', 100),
  (11, 1, 1, 'events-special-events', 'Events / Special Events', 'events', 'Help with occasional church events and special gatherings.', 'Special events may be outside the normal serving rhythm.', 0, 0, 0, 'open', 110),
  (12, 1, 1, 'prayer-ministry-team', 'Prayer / Ministry Team', 'prayer_ministry', 'Pray with and care for people during ministry moments.', 'This role may involve training or a conversation with church leadership.', 0, 1, 0, 'open', 120)
ON CONFLICT(form_id, slug) DO UPDATE SET
  organization_id = excluded.organization_id,
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  public_note = excluded.public_note,
  requires_background_check = excluded.requires_background_check,
  requires_training = excluded.requires_training,
  requires_audition_or_interview = excluded.requires_audition_or_interview,
  recruitment_status = excluded.recruitment_status,
  sort_order = excluded.sort_order,
  is_active = 1,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO serving_area_requirements (
  id,
  organization_id,
  form_id,
  serving_area_id,
  requirement_type,
  label,
  description,
  day_of_week,
  start_time,
  end_time,
  is_mandatory,
  requires_confirmation,
  sort_order
) VALUES
  (1, 1, 1, 1, 'rehearsal', 'Rehearsal availability', 'This role may require rehearsal availability in addition to Sunday service.', NULL, NULL, NULL, 1, 1, 10),
  (2, 1, 1, 1, 'audition_or_interview', 'Worship leader conversation', 'A worship leader may follow up before scheduling this role.', NULL, NULL, NULL, 1, 1, 20),
  (3, 1, 1, 2, 'rehearsal', 'Rehearsal availability', 'This role may require rehearsal availability in addition to Sunday service.', NULL, NULL, NULL, 1, 1, 10),
  (4, 1, 1, 2, 'audition_or_interview', 'Worship leader conversation', 'A worship leader may follow up before scheduling this role.', NULL, NULL, NULL, 1, 1, 20),
  (5, 1, 1, 3, 'rehearsal', 'Rehearsal availability', 'This role may require rehearsal availability in addition to Sunday service.', NULL, NULL, NULL, 1, 1, 10),
  (6, 1, 1, 3, 'audition_or_interview', 'Worship leader conversation', 'A worship leader may follow up before scheduling this role.', NULL, NULL, NULL, 1, 1, 20),
  (7, 1, 1, 4, 'training', 'Slides training', 'Training may be provided before serving independently.', NULL, NULL, NULL, 0, 0, 10),
  (8, 1, 1, 5, 'training', 'Sound training', 'Training may be provided before serving independently.', NULL, NULL, NULL, 0, 0, 10),
  (9, 1, 1, 6, 'availability', 'Sunday morning availability', 'Camera and livestream roles are usually connected to Sunday morning services.', 'sunday', NULL, NULL, 1, 1, 10),
  (10, 1, 1, 6, 'training', 'Camera/livestream training', 'Training may be provided before serving independently.', NULL, NULL, NULL, 0, 0, 20),
  (11, 1, 1, 7, 'background_check', 'Background check required', 'Kids Ministry requires a background check before serving.', NULL, NULL, NULL, 1, 1, 10),
  (12, 1, 1, 7, 'training', 'Kids Ministry training', 'Training may be required before serving independently.', NULL, NULL, NULL, 0, 0, 20),
  (13, 1, 1, 8, 'availability', 'Wednesday night availability', 'Youth Ministry usually meets on Wednesday nights.', 'wednesday', NULL, NULL, 1, 1, 10),
  (14, 1, 1, 8, 'background_check', 'Background check required', 'Youth Ministry requires a background check before serving.', NULL, NULL, NULL, 1, 1, 20),
  (15, 1, 1, 8, 'training', 'Youth Ministry training', 'Training may be required before serving independently.', NULL, NULL, NULL, 0, 0, 30),
  (16, 1, 1, 12, 'training', 'Prayer/ministry team training', 'This role may involve training or a conversation with church leadership.', NULL, NULL, NULL, 0, 0, 10)
ON CONFLICT(id) DO UPDATE SET
  organization_id = excluded.organization_id,
  form_id = excluded.form_id,
  serving_area_id = excluded.serving_area_id,
  requirement_type = excluded.requirement_type,
  label = excluded.label,
  description = excluded.description,
  day_of_week = excluded.day_of_week,
  start_time = excluded.start_time,
  end_time = excluded.end_time,
  is_mandatory = excluded.is_mandatory,
  requires_confirmation = excluded.requires_confirmation,
  sort_order = excluded.sort_order,
  updated_at = CURRENT_TIMESTAMP;
